### ISSUE TITLE
Function `get_true_phases(angle)` returns `None` type object

### ISSUE THREAD

**Issue by rounak-meyur** [openEDI/oedisi-example#85]
The function `get_true_phases` defined in line 52-69 in python script `LocalFeeder/sender_cosim.py` returns a `None` type object.

**Comment by josephmckinsey** [comment]
hmm it appears this happens when the phases are not within the tolerance of 0.2. Would you still fine with rounding to the nearest multiple of pi / 6?

**Comment by rounak-meyur** [comment]
The solution that you have in the `jm/true_phases` branch works fine with no errors. So we can work with this placeholder solution.
